// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations must run over a direct connection (Supabase 5432), not the
    // PgBouncer transaction pooler (6543) which errors on prepared statements.
    url: process.env["DIRECT_URL"],
  },
});
